### ISSUE TITLE
Actividad 1. Infografía 

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/actividad-1-infografia-SANDRAVELASCO#3]
[Infografía Sandra Gabriela Velasco Guzmán-1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-SANDRAVELASCO/files/9420122/Infografia.Sandra.Gabriela.Velasco.Guzman-1.pdf)

**Comment by abicoronel** [comment]
calificaión: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
